export function Words(): string {
  const array: Array<string> = [
   'Vai pra puta que pariu',
   'Com certeza tu tem probleminha na cabeça',
   'Ter a bunda vazada na internet não compensa o vale presente',
   'Isso é madeira de ipê envernizada, ela ficou triste porque você chamou de plástico',
   'Banheiro público transparente',
   'Quero morrer ;-;',
   'UwU significa Uélington wanderley Uchôa',
   'Eu mato minha autoestima todos os dias',
   'Se ele se perdeu falando, imagina eu ouvindo ;-;',
   'Tem um remédio bom pra dormir. É só vc pegar um taco de beisebol e...',
   'Ta fazendo creck creck igual a minha coluna',
   'Foi inventar de emagrecer, agora sofre problema de magro',
   'Alguem tem que ver isso ai né...',
   'ENFIA NO SEU RABO ENTÃO',
   'Sem tempo',
   'Bom dia, meu sal rosa do Himalaia',
   'O mais fundo andar do inferno, onde o fogo é mais quente e tocam jota quest como som ambiente',
   'Nem fudendo',
   'Pirataria pra consumo próprio é legal',
   'Pelo menos uma coisa boa aconteceu no meio da desgraça',
   'E aí? Ja passou a dor do chifre?',
   'Vai nascer um galo, ou um chifre',
   'Até parece que a academia deixou de receber só porque você não foi',
   'Funk de 2009 pra trás não é mais considerado funk, é obra prima da música brasileira',
   'Ja tá de rabo quente logo cedo?',
   'Eu nunca mais vou comprar chuvete na minha vida',
   'Profissão: Kwai Coder',
   'Eu odeio a Blizzard',
   'Seu pai é muito gado',
   'Tá bão já, não precisa entrar em detalhes',
   'Não existe despertador bom o suficiente pra quem não quer acordar',
   'O diabo tem medo de você',
   'Mais grosso que cano de passar bosta',
   'Não precisa entender, só copiar 🪄',
   'Eu tô enrolando ainda',
   'Coloca seu R.A e sua senha de bosta aqui',
   'Na verdade eu só disse 1 porque 0 fica muito humilhante',
   'Não, Paulo. Não vou te mandar nudes',
   'Aí o cara manda uma foto que parece que foi tirada com um celular de 2005 bem na hora que a luz em cima da bateria apaga',
   'Se a banda cover for muito boa, é ruim igual a original',
   'Eu tenho preconceito com esses jogos que se propõem a ser killer de outro. O tanto de WoW killer que apareceu e morreu antes do WoW',
   '25 pila ta dento do orçamento',
   'Toda vez que eu vejo o Maizena, eu me recuso a acreditar que temos a mesma idade. O cara ta gordola e calvão. Parece adulto de verdade',
   'Naturalizado Carioca',
   'Me passa o nome completo da sua mãe pra eu ver um negocio',
   '4k mais pobre, mas pelo menos esclarecido',
   'Ninguem paga exame de HIV esperando que ele dê positivo pra valer a pena o investimento',
   'Eu respeito analistas de comportamento. Psicanalistas, por outro lado, eu acho uma piada',
   'Quem vai te dizer isso é o psiquiatra',
   'Mipadres sempre é uma boa opção',
   'Eu sei que vc deve ter gasto uma nota em Hearthstone',
   'Cabelo cresce de novo. Bom, em algumas pessoas não'
  ];
  const randomIndex = Math.floor(Math.random() * array.length);
  return array[randomIndex];
}
